import { streamText, convertToModelMessages, type UIMessage } from "ai";
import { model, systemPrompt } from "@/lib/ai/config";

/**
 * API Route Handler for FlyBot streaming chat endpoint.
 * Accepts POST requests containing a list of UIMessage objects and returns
 * a streaming response generated by Google Gemini 2.0 Flash model.
 *
 * GEMINI_API_KEY is read exclusively from process.env.GEMINI_API_KEY.
 */
export async function POST(req: Request) {
  try {
    const body = await req.json();
    const messages: UIMessage[] = body.messages ?? [];

    const result = streamText({
      model,
      system: systemPrompt,
      messages: await convertToModelMessages(messages),
    });

    return result.toUIMessageStreamResponse();
  } catch (error) {
    console.error("FlyBot API Route Error:", error);
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : "An error occurred",
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
